import { spawn } from "node:child_process";

/** The narrow transcoding seam keeps the media route easy to test. */
export interface SonosTranscoder {
  transcodeToMp3(sourcePath: string, outputPath: string): Promise<void>;
}

/**
 * Runs FFmpeg without a shell and emits a bounded, constant-bitrate MP3.
 *
 * The output path is generated by the media service, rather than accepted from
 * a request, so it is safe to pass as a normal argv value. `-minrate` and
 * `-maxrate` make the LAME encode CBR while keeping the bitrate at 320 kbps.
 */
export class FfmpegSonosTranscoder implements SonosTranscoder {
  constructor(private readonly executable = "ffmpeg") {}

  async transcodeToMp3(sourcePath: string, outputPath: string): Promise<void> {
    const args = [
      "-nostdin",
      "-hide_banner",
      "-loglevel",
      "error",
      "-y",
      "-i",
      sourcePath,
      "-map",
      "0:a:0",
      "-vn",
      "-codec:a",
      "libmp3lame",
      "-b:a",
      "320k",
      "-minrate",
      "320k",
      "-maxrate",
      "320k",
      "-bufsize",
      "320k",
      "-f",
      "mp3",
      outputPath,
    ];

    await runProcess(this.executable, args);
  }
}

function runProcess(command: string, args: string[]): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      shell: false,
      windowsHide: true,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let stderr = "";
    child.stderr?.setEncoding("utf8");
    child.stderr?.on("data", (chunk: string) => {
      stderr = `${stderr}${chunk}`.slice(-2_000);
    });
    child.once("error", reject);
    child.once("close", (code, signal) => {
      if (code === 0) {
        resolve();
        return;
      }
      reject(new Error(`FFmpeg transcoding failed (${code ?? `signal ${signal ?? "unknown"}`}): ${stderr}`));
    });
  });
}
